GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/blogs/67c2ee98bfd7e820dd7cd659

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: Bearer token

{
  "title": "Test",
  "author": "Test",
  "url": "http://test.com",
  "likes": 0
}

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Test2",
  "author": "Test2",
  "url": "http://test2.com",
  "likes": 0
}

###
PUT http://localhost:3001/api/blogs/6a385cace3088671e7a2e7dd
Content-Type: application/json

{
  "title": "Test",
  "author": "New",
  "url": "http://new.com",
  "likes": 100
}

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "testuser",
  "name": "Test User",
  "password": "testpassword"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "testuser",
  "password": "testpassword"
}

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "root",
  "name": "Superuser",
  "password": "root"
}

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "root",
  "password": "root"
}

###
DELETE http://localhost:3001/api/blogs/6a3b11ef636a3608383fc8d9
Authorization: Bearer token

